
version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - teleport-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      # Database connection
      - DB_HOST=postgres
      - DB_NAME=teleport
      - DB_USER=teleport
      - DB_PASSWORD=teleport123
      - DEBUG=False
      # Teleport authentication
      - SECRET_KEY=${SECRET_KEY:-default_secret_key}
      - AUTH_USERNAME=${AUTH_USERNAME:-admin}
      - AUTH_PASSWORD_HASH=${AUTH_PASSWORD_HASH}
      # SSH configuration for teleport
      - SSH_HOSTS=${SSH_HOSTS:-'{"default":"localhost"}'}
      - SSH_PORT=${SSH_PORT:-22}
      - SSH_USER=${SSH_USER:-root}
      - SSH_KEY_PATH=${SSH_KEY_PATH:-/app/ssh_key}
    volumes:
      - ${SSH_KEY_LOCAL_PATH:-./ssh_key}:${SSH_KEY_PATH:-/app/ssh_key}:ro
    depends_on:
      - postgres
    # Not exposing backend port to host machine, only accessible within Docker network
    networks:
      - teleport-network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=teleport
      - POSTGRES_USER=teleport
      - POSTGRES_PASSWORD=teleport123
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - teleport-network

networks:
  teleport-network:
    driver: bridge

volumes:
  postgres-data:
